Changed tests to use chai, chai and mocha now in package.json
aowenmeehanwork/CapabilityViewer pull request #19
Opened 2019-09-11 14:45 UTC by aowenmeehanwork

Tests now check to see if data coming in from the API is valid

2019-09-12 10:03 UTC, clarebuckley approved these changes
All tests pass

2019-09-18 15:09 UTC, micalexis requested changes
address the comments

2019-09-18 15:09 UTC, micalexis commented on src/backend-api/test/api_tests.js
>              if (err) console.log(err);
wrap in brackets

2019-09-18 15:09 UTC, micalexis commented on src/backend-api/test/api_tests.js
> +        if (err) console.log(err);
same as above

2019-09-18 15:14 UTC, aowenmeehanwork commented
Outdated pull request, this functionality is implemented in US011/view-job-family-capability with appropriate requested changes to logging. Closing pull request now.

2019-09-18 15:14 UTC, closed without merging