View training grouped by category for a specific role (#47)
aowenmeehanwork/CapabilityViewer pull request #48
Opened 2019-09-18 13:51 UTC by clarebuckley

2019-09-18 15:03 UTC, micalexis requested changes

2019-09-18 15:03 UTC, micalexis commented on e2e/src/app.e2e-spec.ts
> +  let bandDetailPage: BandDetailViewerPage;
where are these being used?

2019-09-18 15:03 UTC, micalexis commented on src/app/detail-viewer/detail-viewer.component.ts
> +        if(response != null){
```JAVASCRIPT
if(response){
}
```

2019-09-18 15:03 UTC, micalexis commented on src/backend-api/index.js
> +        if(err) return handleError(err);
put in brackets

2019-09-18 15:03 UTC, micalexis commented on src/backend-api/index.js
>          if(err) return handleError(err);
same as above

2019-09-20 09:17 UTC, closed without merging

2019-09-20 09:17 UTC, clarebuckley commented
Closed due to renaming branch to feature/view-role